services:
  django_app:
    build: .
    env_file:
      - dpp.env
    command: sh -c "python manage.py makemigrations && python manage.py migrate  && python manage.py runserver 0.0.0.0:$$DJ_HOST"
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - "POSTGRES_PASSWORD=postgres"
      - POSTGRES_DB=postgres
    volumes:
      - postgres_vol:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 2s
      retries: 5

volumes:
  postgres_vol:

