services:
  django_app:
    build: .
    env_file:
      - dj.env
    depends_on:
      - database
    ports:
      - 8000:8000
  database:
    image: postgres
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres
    ports:
      - 5432:5432